Fix Missing M_PI
Fix compile error with GCC 7.4.0 on Ubuntu 18.04.3 of the kind:
```
fft.c:223:63: error: use of undeclared identifier 'M_PI'
```

by including the general defines from `zpic.h`.