Linux: `PATH_MAX` undeclared
Fix the missing POSIX define for `PATH_MAX` by including
`linux/limits.h` on Linux.

Fixes GCC 7.4.0 errors on Ubuntu 18.04.3 LTS of the kind:
```
main.c: In function ‘run_sim’:
main.c:53:12: error: ‘PATH_MAX’ undeclared (first use in this function); did you mean ‘INT8_MAX’?
  char root[PATH_MAX];
```